### ISSUE TITLE
Code reorg

### ISSUE THREAD

**Issue by keevindoherty** [RobustFieldAutonomyLab/la3dm#1]
Currently substantial redundancy in data structures and functions.

Many functions can be broken out into `common/` e.g. `bbox(cloud, lim_min, lim_max)` among others.

Furthermore, GPOctoMap and BGKOctoMap share mostly the same data structures; this can definitely be cleaned up, rather than redefining everything under separate namespaces, as is currently the case.

**Comment by baishibona** [comment]
@keevindoherty thanks for the updates! and looking forward to it!
