### ISSUE TITLE
use bgkoctomap to update original existed map

### ISSUE THREAD

**Issue by zhangkui669** [RobustFieldAutonomyLab/la3dm#2]
Hi, 
     if I already have a initial map, how can I do mapping with this initial map?

**Comment by keevindoherty** [comment]
Hi,
Grid cells in BGKOctoMap maintain the "alpha" and "beta" hyperparameters (see paper [here](http://personal.stevens.edu/~benglot/Doherty_Wang_Englot_ICRA_2017.pdf), Eqns 1-6 are relevant).
So there isn't a perfect way to take an arbitrary probabilistic occupancy map built using a different method and turn it into a BGK map; the underlying representation is different.

That said, one heuristic thing you could do is turn your map into a set of "occupied" and "free" point clouds (for example, by taking the grid cell centers), and inserting those point clouds into a new BGK map (may require some small modifications to the functions for inserting point clouds). This would set up your "alpha's" and "beta's" to values that reflect your prior knowledge. Does that kind of make sense?
